<template>
  <div class="museum-page page-container"><header><span class="eyebrow">CULTURE & FORM · 泥塑观察</span><h1>在造型与色彩之间，读懂泥人</h1><p>以惠山泥人为主线，结合其他地区的泥塑资料，观察人物、动物与戏曲题材的不同表达。</p><RouterLink to="/model-library">浏览三维模型与部件 ↗</RouterLink></header><EditorialCollection />
    <section><div class="section-heading"><div><h2>五种泥塑题材</h2><p>从人物、戏曲与动物形象出发，认识泥塑的造型与色彩。</p></div><el-input v-model="keyword" placeholder="搜索题材或名称" clearable /></div><p class="review-note">实物照片用于题材观察，与本站数字作品分别展示。具体作品信息请查阅图片原始发布页面。</p><nav class="tabs"><button v-for="group in groups" :key="group" :class="{active:selectedGroup===group}" @click="selectedGroup=group">{{ group }}</button></nav>
      <div class="exhibit-grid"><article v-for="item in filtered" :key="item.id"><button class="picture" :aria-label="`阅读${item.name}资料`" @click="selected=item;galleryIndex=0"><img :src="photo(item.image)" :alt="item.name+'题材图片'" loading="lazy" /><span>{{ item.group }}</span></button><div class="body"><h3>{{ item.name }}</h3><p>{{ item.intro }}</p><button class="read" @click="selected=item;galleryIndex=0">观察细节与来源 ↗</button></div></article></div><p v-if="!filtered.length" class="empty">没有匹配资料，请调整搜索词或分类。</p>
    </section>
    <section class="craft-section"><h2>从工作室到指尖：工艺图片参考</h2><p>从泥坯修整、模具运用到手工彩绘，观察工匠如何让形体与色彩逐步成形。照片展示不同工艺环节，可与题材图片对照阅读。</p><div class="craft-grid"><figure v-for="(item,index) in craftImages" :key="item.id"><button class="craft-open" :aria-label="`放大查看${item.title}`" @click="craftIndex=index"><img :src="photo(item.id)" :alt="item.title+'资料参考图'" loading="lazy" /><span>点击放大 ↗</span></button><figcaption><strong>{{ item.title }}</strong><small>{{ item.source }}</small></figcaption></figure></div></section>
    <el-image-viewer v-if="craftIndex!==null" :url-list="craftImages.map(item=>photo(item.id))" :initial-index="craftIndex" :teleported="true" @close="craftIndex=null" />
    <el-dialog :model-value="!!selected" :title="selected?.name" width="900px" @update:model-value="value=>{if(!value)selected=null}"><div v-if="selected" class="exhibit-detail"><div><img class="main-photo" :src="photo(selected.gallery[galleryIndex])" :alt="selected.name+'资料图片'" /><div class="gallery"><button v-for="(id,index) in selected.gallery" :key="id" :aria-label="`查看图片 ${index+1}`" :aria-pressed="galleryIndex===index" @click="galleryIndex=index"><img :src="photo(id)" :alt="'图片 '+(index+1)" /></button></div></div><div><span class="eyebrow">{{ selected.group }} · 题材赏析</span><p v-for="paragraph in selected.paragraphs || [selected.story]" :key="paragraph">{{ paragraph }}</p><h3>可以怎样观察？</h3><ul><li v-for="detail in selected.details" :key="detail">{{ detail }}</li></ul><h3>资料来源</h3><a v-for="source in selected.sources" :key="source.url" :href="source.url" target="_blank" rel="noopener noreferrer">{{ source.title }} ↗</a><p class="review-note">照片版权归原权利人所有，作品名称与作者信息以原始发布页面为准。</p><RouterLink to="/shop/designs">探索由传统题材启发的原创文创概念</RouterLink></div></div></el-dialog>
  </div>
</template>
<script setup>
import {computed,ref} from 'vue'
import content from '@/content/editorial.json'
import EditorialCollection from '@/components/EditorialCollection.vue'
const keyword=ref(''),selectedGroup=ref('全部'),selected=ref(null),galleryIndex=ref(0),craftIndex=ref(null)
const groups=['全部','惠山泥人','地域对照']
const craftImages=[{id:11,title:'工作室环境',source:'工艺参考：无锡惠山泥人厂《百年芳华 沃土奇葩》'},{id:12,title:'手工彩绘',source:'工艺参考：《惠山泥人工艺学》连载（01）'},{id:13,title:'颜料与色彩',source:'工艺参考：《惠山泥人工艺学》连载（11）'},{id:14,title:'面部彩绘',source:'工艺参考：《惠山泥人工艺学》连载（01）'},{id:15,title:'泥坯修整',source:'工艺参考：《惠山泥人工艺学》连载（12）'},{id:16,title:'模具与形体',source:'工艺参考：《惠山泥人工艺学》连载（13）'}]
const photo=id=>`${import.meta.env.BASE_URL}content/material-${String(id).padStart(2,'0')}.webp`
const filtered=computed(()=>content.exhibits.filter(item=>(selectedGroup.value==='全部'||item.group===selectedGroup.value)&&[item.name,item.intro,item.group].join(' ').includes(keyword.value.trim())))
</script>
<style scoped>
.craft-open{position:relative;width:100%;padding:0;border:0;background:none;border-radius:10px}.craft-open:focus-visible{outline:3px solid #2d6172;outline-offset:3px}.craft-open span{position:absolute;bottom:8px;right:8px;background:#fffef0e8;color:#365e58;padding:4px 8px;border-radius:5px;font-size:12px}.craft-section{margin-top:48px;border-top:1px solid #ded5c2;padding-top:24px}.craft-section>p{color:#67726a;line-height:1.8;font-size:14px}.craft-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.craft-grid figure{margin:0}.craft-grid img{width:100%;height:180px;object-fit:contain;background:#eee9e0;border-radius:10px}.craft-grid figcaption{padding:10px 0;color:#365e58}.craft-grid small{display:block;margin-top:6px;color:#7b786c;line-height:1.6}@media(max-width:600px){.craft-grid{grid-template-columns:1fr 1fr}.craft-grid img{height:130px}}
.museum-page{max-width:1240px}.museum-page>header{padding:24px 0}.eyebrow{font-size:12px;letter-spacing:1px;color:#a55a3c}h1{font-size:36px;margin:12px 0;color:#2d6172}header p,.section-heading p{color:#67726a;line-height:1.8}.museum-page a{color:#2d6172;text-decoration:underline;text-underline-offset:3px}.museum-page :deep(.editorial){padding:24px 0 40px}h2{color:#365e58}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:24px}.section-heading .el-input{width:260px;max-width:100%}.review-note{background:#f5efe3;padding:12px 16px;font-size:13px;color:#7b6647;line-height:1.8}.tabs{display:flex;gap:10px;margin:24px 0}button{font:inherit;cursor:pointer}.tabs button{border:1px solid #d9ddd6;border-radius:24px;padding:9px 20px;background:white;color:#536b60}.tabs .active{background:#2d6172;color:white}.exhibit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.exhibit-grid article{border:1px solid #e7e1d5;background:white;border-radius:12px;overflow:hidden}.picture{position:relative;width:100%;padding:0;border:0;background:#eee9e0;height:280px}.picture img{width:100%;height:100%;object-fit:contain}.picture span{position:absolute;left:12px;bottom:12px;background:#fffef3e6;padding:5px 10px;border-radius:5px;color:#365e58;font-size:12px}.body{padding:20px}.body h3{margin:0;color:#365e58}.body p{line-height:1.8;color:#67726a;font-size:14px}.read{border:0;background:none;padding:8px 0;color:#a55a3c}.exhibit-detail{display:grid;grid-template-columns:1fr 1fr;gap:24px;line-height:1.9}.main-photo{width:100%;height:400px;object-fit:contain;background:#eee9e0;border-radius:10px}.gallery{display:flex;gap:8px;margin-top:10px}.gallery button{background:white;border:2px solid transparent;padding:2px}.gallery button[aria-pressed=true]{border-color:#2d6172}.gallery img{width:64px;height:64px;object-fit:cover}.exhibit-detail a{display:block}.empty{text-align:center;padding:40px;color:#67726a}@media(max-width:900px){.exhibit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){h1{font-size:28px}.exhibit-grid,.exhibit-detail{grid-template-columns:1fr}.section-heading{align-items:start;flex-direction:column;gap:5px}.section-heading .el-input{width:100%}.main-photo{height:300px}.tabs button{padding:8px 14px}}
</style>
