<template>
  <div class="page-container account"><h1>我的商城</h1><RouterLink to="/shop">返回商品选购</RouterLink><p v-if="error" role="alert">{{ error }} <el-button @click="refresh">重试</el-button></p><el-tabs v-model="tab">
    <el-tab-pane label="我的订单" name="orders"><el-select v-model="status" clearable placeholder="全部状态" @change="page=1;loadOrders()"><el-option v-for="value in ['待确认','待发货','已发货','已完成','已取消']" :key="value" :value="value" :label="value" /></el-select><p>当前订单等待商家确认，不提供线上支付。物流信息是商家填写的运单记录，并非实时轨迹。</p><article v-for="order in orders" :key="order.id"><h3>{{ order.id.slice(0,8) }} · {{ order.status }}</h3><p>{{ order.created_at }} · ¥{{ order.total.toFixed(2) }}</p><p>{{ order.receiver }} · {{ order.phone }} · {{ order.address }}</p><p v-if="order.tracking_number">{{ order.carrier }} · {{ order.tracking_number }}</p><div v-for="item in order.items" :key="item.product_id" class="order-item"><span>{{ item.name }} × {{ item.quantity }}</span><el-button v-if="order.status==='已完成'" @click="reviewOrder=order;reviewProduct=item;reviewText='';rating=5">评价商品</el-button></div><el-button v-if="order.status==='待确认'" :disabled="busy" @click="cancel(order)">取消订单</el-button><el-button v-if="order.status==='已发货'" :disabled="busy" @click="receive(order)">确认收货</el-button></article><p v-if="!orders.length">暂无符合条件的订单</p><el-pagination v-model:current-page="page" :page-size="12" :total="total" layout="prev,pager,next" @current-change="loadOrders" /></el-tab-pane>
    <el-tab-pane label="商品收藏" name="favorites"><article v-for="product in favorites" :key="product.id"><h3>{{ product.name }}</h3><p>¥{{ product.price.toFixed(2) }} · {{ product.stock>0?'有库存':'暂无库存' }}</p><el-button @click="unfavorite(product.id)">取消收藏</el-button></article><p v-if="!favorites.length">还没有收藏商品，可在商品卡片中收藏。</p></el-tab-pane>
    <el-tab-pane label="收货地址" name="addresses"><p>最多保存20个地址；订单提交时保留地址快照，之后修改地址不会改变历史订单。</p><article v-for="address in addresses" :key="address.id"><h3>{{ address.receiver }} <el-tag v-if="address.is_default">默认</el-tag></h3><p>{{ address.phone }} · {{ address.address }}</p><el-button @click="addressForm={...address}">编辑</el-button><el-button @click="deleteAddress(address.id)">删除</el-button></article><el-form label-position="top" @submit.prevent="saveAddress"><el-form-item label="收货人"><el-input v-model="addressForm.receiver" maxlength="80" /></el-form-item><el-form-item label="联系电话"><el-input v-model="addressForm.phone" maxlength="30" /></el-form-item><el-form-item label="详细地址"><el-input v-model="addressForm.address" type="textarea" maxlength="500" /></el-form-item><el-checkbox v-model="addressForm.is_default">设为默认地址</el-checkbox><div class="actions"><el-button type="primary" :loading="busy" @click="saveAddress">保存地址</el-button><el-button @click="resetAddress">新建地址</el-button></div></el-form></el-tab-pane>
  </el-tabs><el-dialog :model-value="!!reviewOrder" title="评价已收货商品" width="560px" @update:model-value="value=>{if(!value)reviewOrder=null}"><p>{{ reviewProduct?.name }}</p><el-rate v-model="rating" /><el-input v-model="reviewText" type="textarea" :rows="4" maxlength="1000" show-word-limit placeholder="填写真实使用感受" /><template #footer><el-button type="primary" :loading="busy" @click="submitReview">提交评价</el-button></template></el-dialog></div>
</template>
<script setup>
import { ref,onMounted } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import request from '@/api/index'
const tab=ref('orders'),orders=ref([]),favorites=ref([]),addresses=ref([]),status=ref(''),page=ref(1),total=ref(0),busy=ref(false),error=ref('')
const addressForm=ref({}),reviewOrder=ref(null),reviewProduct=ref(null),reviewText=ref(''),rating=ref(5)
const resetAddress=()=>{addressForm.value={receiver:'',phone:'',address:'',is_default:false}}
resetAddress()
const loadOrders=async()=>{try{const r=await request.get('/shop/orders',{params:{page:page.value,per_page:12,status:status.value||undefined}});orders.value=r.data;total.value=r.meta.pagination.total}catch{error.value='订单加载失败，请重试'}}
const refresh=async()=>{error.value='';try{await loadOrders();favorites.value=(await request.get('/shop/favorites')).data;addresses.value=(await request.get('/shop/addresses')).data}catch{error.value='无法加载商城资料，请重试'}}
const action=async fn=>{if(busy.value)return;busy.value=true;try{await fn();await refresh()}catch{/* 拦截器显示错误 */}finally{busy.value=false}}
const saveAddress=()=>action(async()=>{const row=addressForm.value;await request[row.id?'put':'post']('/shop/addresses'+(row.id?'/'+row.id:''),row);resetAddress();ElMessage.success('地址已保存')})
const deleteAddress=async id=>{try{await ElMessageBox.confirm('删除此收货地址？','地址管理');await action(()=>request.delete('/shop/addresses/'+id))}catch{/* 取消 */}}
const unfavorite=id=>action(()=>request.delete('/shop/favorites/'+id))
const cancel=async order=>{try{await ElMessageBox.confirm('取消待确认订单并释放库存？','取消订单');await action(()=>request.post(`/shop/orders/${order.id}/cancel`))}catch{/* 取消 */}}
const receive=async order=>{try{await ElMessageBox.confirm('请确认已收到商品，确认后可以评价。','确认收货');await action(()=>request.post(`/shop/orders/${order.id}/receive`))}catch{/* 取消 */}}
const submitReview=()=>action(async()=>{await request.post(`/shop/orders/${reviewOrder.value.id}/reviews`,{product_id:reviewProduct.value.product_id,rating:rating.value,content:reviewText.value});reviewOrder.value=null;ElMessage.success('评价已发布')})
onMounted(refresh)
</script>
<style scoped>.account{max-width:1000px}.account a{color:#2d6172}.account article{background:white;padding:20px;border:1px solid #e7e1d5;border-radius:12px;margin:20px 0;overflow-wrap:anywhere}.order-item{display:flex;justify-content:space-between;gap:16px;margin:12px 0}.account p{color:#66756e;line-height:1.8}.account .el-form{max-width:600px;background:white;padding:20px;border-radius:12px}.actions{margin-top:18px;display:flex;gap:12px}.account :deep(.el-pagination){flex-wrap:wrap}</style>
