"""add ai_tasks table

Revision ID: 0f6b0abfa81e
Revises: ec81fb550152
Create Date: 2026-08-31 22:47:38.694298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6b0abfa81e'
down_revision = 'ec81fb550152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('input_url', sa.String(length=500), nullable=True),
    sa.Column('external_task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    # 显式命名 FK: 后续 1bfd534f0826 需按名重建 artwork FK(ondelete SET NULL)，
    # 无名约束在 SQLite batch / MySQL 自动命名下均无法按 fk_ai_tasks_artwork_id 定位
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name='fk_ai_tasks_artwork_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ai_tasks_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tasks_artwork_id'), ['artwork_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_external_task_id'), ['external_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_ai_tasks_external_task_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_tasks_artwork_id'))

    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
