"""add artwork table

Revision ID: ec81fb550152
Revises: bd3c732cc20f
Create Date: 2026-08-31 20:33:40.396925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec81fb550152'
down_revision = 'bd3c732cc20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('model_url', sa.String(length=500), nullable=True),
    sa.Column('model_format', sa.Enum('glb', 'gltf', 'obj', 'stl'), nullable=True),
    sa.Column('model_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_params', sa.JSON(), nullable=True),
    sa.Column('style_analysis', sa.JSON(), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=256), nullable=True),
    sa.Column('blockchain_tx_id', sa.String(length=256), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('allow_download', sa.Boolean(), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artworks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artworks_user_id'))
        batch_op.drop_index(batch_op.f('ix_artworks_created_at'))

    op.drop_table('artworks')
    # ### end Alembic commands ###
